// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace InvoiceWebApi.Models
{
    public partial class InvoicedbContext : DbContext
    {
        public InvoicedbContext()
        {
        }

        public InvoicedbContext(DbContextOptions<InvoicedbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Invoice> Invoice { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=LAPTOP-RT1ABEOL\\SQLEXPRESS;Initial Catalog=InvoiceDB;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<Invoice>(entity =>
            {
                entity.Property(e => e.BIC).IsUnicode(false);

                entity.Property(e => e.Date).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.InvoiceNumber).IsUnicode(false);

                entity.Property(e => e.InvoiceSender).IsUnicode(false);

                entity.Property(e => e.RecipientIBAN).IsUnicode(false);

                entity.Property(e => e.RecipientName).IsUnicode(false);

                entity.Property(e => e.Reference).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}