// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InvoiceWebApi.Models
{
    public partial class Invoice
    {
        public long Id { get; set; }
        [Required]
        [StringLength(50)]
        public string InvoiceSender { get; set; }
        [Required]
        [StringLength(50)]
        public string RecipientName { get; set; }
        [Required]
        [StringLength(18)]
        public string RecipientIBAN { get; set; }
        [Required]
        [StringLength(20)]
        public string Reference { get; set; }
        [Required]
        [StringLength(10)]
        public string InvoiceNumber { get; set; }
        [Required]
        [StringLength(8)]
        public string BIC { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Total { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DueDay { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
    }
}